language: scala
sudo: true
services:
  - postgresql
  - docker
before_install:
  - docker pull mysql
  - docker run --name mysql -d -p 127.0.0.1:3307:3306 mysql
  - docker pull wnameless/oracle-xe-11g
  - docker run --name oracle -d -p 127.0.0.1:1521:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g
  - docker ps -a
  - docker inspect mysql
  - docker inspect oracle
scala:
  - 2.11.8
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - jtysper-ORACLE_12C
before_script:
  - psql -c 'create database docker;' -U postgres
addons:
  postgresql: "9.4"
script: "./build.sh"