language: scala
sudo: false
scala:
  - "2.10.5"
  - "2.11.6"
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
script: "./build.sh"