language: scala
sudo: false
scala:
  - "2.11.7"
jdk:
  - oraclejdk8
branches:
  only:
    - akka-2.4.0-xx
before_script:
  - psql -c 'create database docker;' -U postgres
addons:
  postgresql: "9.4"
script: "./build.sh"
notifications:
  email:
    - dnvriend@gmail.com