mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3306:3306"

oracle:
  image: alexeiled/docker-oracle-xe-11g
  ports:
    - "1521:1521"

postgres:
  image: postgres:9.4
  environment:
    - "POSTGRES_USER=docker"
    - "POSTGRES_PASSWORD=docker"
  ports:
    - "5432:5432"

h2:
  image: viliusl/ubuntu-h2-server
  ports:
    - "1522:1521"